Repository VerWiki/VerWikiApp, pull requests merged in 2021-06, with the labels that each got.

#25 Scroll to top whenever a new node is right-clicked upon
  frontend/src/components/InfoWindow/InfoWindow.jsx
Labels: feature/enhancement

#26 Enable "zoom" feature by changing the max depth dynamically
  frontend/src/components/TreeViewer/TreeViewer.jsx
  frontend/src/utils/ZoomManager.js
  frontend/src/utils/config.js
  frontend/src/utils/utils.js
Labels: feature/enhancement

#27 Refactor constants into config file; move functions to utils; style improvements
  frontend/src/components/InfoWindow/InfoWindow.jsx
  frontend/src/components/NodePathHistory/NodePathHistory.jsx
  frontend/src/components/NodePathHistory/NodePathHistory.module.css
  frontend/src/utils/Logger.js
  frontend/src/utils/config.js
  frontend/src/utils/utils.js
Labels: tech debt

#28 Feature/name truncation
  frontend/src/App.css
  frontend/src/components/InfoWindow/InfoWindow.jsx
  frontend/src/components/Navigation/Navigation.module.css
  frontend/src/components/NodePathHistory/NodePathHistory.jsx
  frontend/src/components/NodePathHistory/NodePathHistory.module.css
  frontend/src/components/Tree/Tree.jsx
  frontend/src/components/TreeViewer/TreeViewer.jsx
  frontend/src/components/TreeViewer/TreeViewer.module.css
  frontend/src/utils/config.js
Labels: bug, feature/enhancement
